### ISSUE TITLE
Can't ssh in the VM

### ISSUE THREAD

**Issue by pvledoux** [rlerdorf/php7dev#29]
Hi, I have an error when trying to ssh in the vm:

```
▶ vagrant ssh
/Users/pvl/Projects/SANDBOX/php7dev/Vagrantfile:23:in `read': No such file or directory - /Users/pvl/Projects/SANDBOX/php7dev/src/php7dev.yaml (Errno::ENOENT)
    from /Users/pvl/Projects/SANDBOX/php7dev/Vagrantfile:23:in `block in <top (required)>'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/v2/loader.rb:37:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/v2/loader.rb:37:in `load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/loader.rb:103:in `block (2 levels) in load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/loader.rb:97:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/loader.rb:97:in `block in load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/loader.rb:94:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/loader.rb:94:in `load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/vagrantfile.rb:28:in `initialize'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:689:in `new'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:689:in `vagrantfile'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:441:in `host'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:207:in `block in action_runner'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:33:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:33:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:428:in `hook'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:671:in `unload'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:177:in `ensure in <main>'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:177:in `<main>'                       14d  ⍉ 14d14d  ⍉                               14d 14d  ⍉
```

**Comment by rlerdorf** [comment]
Why is it looking for php7dev.yaml in the src/ directory? Do you have some weird environment variable set?
Vagrantfile line 23 just says: 

```
Php7dev.configure(config, YAML::load(File.read(php7devYamlPath)))
```

And that path comes from line 6 which is:

```
php7devYamlPath = File.expand_path("./php7dev.yaml")
```

Look for any VAGRANT_\* env variables you may have set and unset them. Or set them correctly.

**Comment by pvledoux** [comment]
I rebooted, reinstalled and that did the trick. Weird... Cheers!
